version: '3.8'
services:
    postgres:
      image: postgres
      container_name: postgres
      restart: always
      networks:
         discord_network:
      ports:
        - "5432:5432" 
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
      volumes:
        - postgres:/var/lib/postgresql/data
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      networks:
         discord_network:
      depends_on:
        - postgres
      command:
        - CREATE DB Blog_App
    redis:
      image: redis:alpine
      command:
        - redis-server
      ports:
        - "6379:6379"
      container_name: redis
      networks:
         discord_network:
      volumes:
        - redis-data:/data
        - redis-conf:/usr/local/etc/redis/redis.conf
    elastic-search:
      image: elasticsearch:8.5.3
      container_name: es-container
      environment:
        - node.name=es-container
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - elastic-data:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
      networks:
         discord_network:
    kibana:
      container_name: kb-container
      image: kibana:8.5.3
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      networks:
         discord_network:
      depends_on:
        - elastic-search
      ports:
        - "5601:5601"
    app:
      build:
        context: .
        dockerfile: Dockerfile
        target: development
      depends_on:
        - postgres
        - elastic-search
      environment:
        - ELASTICSEARCH_NODE=http://elastic-search:9200
        - DATABASE_URL=postgresql://admin:admin@postgres/discord?schema=public
      ports:
        - "5000:5000"
      env_file:
        - ./.env
      volumes:
        - .:/usr/src/app

      networks:
        discord_network:
volumes:
  postgres:
  pgadmin-data:
  redis-data:
  redis-conf:
  elastic-data:
    driver: local
networks:
    discord_network:
      driver: bridge
      internal: true
